name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Update on push to main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (automatically provided)
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Basic config
          user: maddynenn
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Output file
          filename: metrics.svg
