name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Update on push to main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: maddynenn
          template: classic
          base: ""  # This removes header, activity, etc.
    
    # Only the isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
    
          filename: metrics.svg
